version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musica
    volumes:
      - ./main.sql:/docker-entrypoint-initdb.d/main.sql
    ports:
      - 3306:3306